# Generated by Django 2.1.4 on 2019-01-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='image_url',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='task_condition',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='task_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='task_type',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
